# fly.toml app configuration file generated for helsinki-part3 on 2024-02-21T12:15:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helsinki-part3'
primary_region = 'yyz'

[build]

[env]
  PORT = "3001" # add this
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 3001 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
